# Generated by Django 4.2.5 on 2023-12-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=122)),
                ('LastName', models.CharField(max_length=122)),
                ('Province', models.CharField(max_length=122)),
                ('Address', models.CharField(max_length=122)),
                ('Address2', models.CharField(max_length=122)),
                ('EmailAddress', models.CharField(max_length=122)),
                ('PhoneNumber', models.IntegerField(max_length=122)),
                ('City', models.CharField(max_length=122)),
                ('desc', models.TextField()),
            ],
        ),
    ]
